version: '3'
services:
  nginx:
    build:
      context: ./docker
      dockerfile: nginx.dockerfile
    volumes:
      - ./:/app
    depends_on:
      - php-fpm
    ports:
      - ${NGINX_PORT}

  php-fpm:
    user: ${UID}
    build:
      context: ./docker
      dockerfile: php-fpm.dockerfile
    volumes:
      - ./:/app

  mysql:
    image: mysql:5.7
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_ALLOW_EMPTY_PASSWORD

volumes:
  mysql_data:
    external:
      name: ${MYSQL_VOLUME}
